version: '3.7'

services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - 80:8080
    restart: always
    tty: true
    command:
      - /docker-entrypoint.sh
    volumes:
      - ./app/my-vue-app:/app
    
  back:
    container_name: back
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    command:
      - /docker-entrypoint.sh
    volumes:
      - ./app/python:/app