version: '3.7'

services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    restart: always
    tty: true
    volumes:
      - ./app:/app